apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "60sTqhgfegytKNDs22LnbDGECDz23yepCsyjK2IgzRxylqJTQAiDhS662QQfyrq8\nMy4gRsMYMglhCIxAbsIupwma7CK2ll+Nty2Zq+LnTD2k0uIMkvh4cjsEB/ERv3qE\n1tLvwWdfOIHuHZtfwAVpKxn4bnJk4tEkUMexz2FW69A="
